### ISSUE TITLE
Occasional Embrace-related IllegalStateException crash in 6.10.0

### ISSUE THREAD

**Issue by JakeSteam** [embrace-io/embrace-android-sdk#1296]
### Describe the bug
We released an updated Android app yesterday that updates to SDK 6.10.0 & customises our Embrace setup, and noticed a crash on Crashlytics that isn't reported in Embrace.

### Steps to reproduce
Unknown, only happened to 1 user so far whilst viewing our initial onboarding screens.

### Environment
* Android version: 23
* Embrace SDK version: 6.10.0
* Emulator or physical device: Physical
* Project: "Seatfrog", app ID `MWiq6`, Production.

### Stack trace

```
Fatal Exception: java.lang.IllegalStateException
Check failed.
androidx.compose.ui.node.DelegatableNodeKt.visitAncestors (DelegatableNode.kt:78)
androidx.core.app.ComponentActivity.dispatchKeyEvent (ComponentActivity.java:144)

io.embrace.android.embracesdk.compose.internal.EmbraceWindowCallback.dispatchKeyEvent (EmbraceWindowCallback.kt)

com.android.internal.policy.DecorView.dispatchKeyEvent (DecorView.java:400)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1009)
```
![image](https://github.com/user-attachments/assets/991ef9ff-c519-4a5e-93f4-04d84401a44d)

### Project config

We use compose dependency injection swazzling on prod builds only with this block in our `build.gradle.kts`:

```
    // https://embrace.io/docs/android/features/build-options/
    swazzler {
        disableComposeDependencyInjection.set(false)  // https://embrace.io/docs/android/features/jetpack-compose/#set-local-config-and-swazzler-block
        variantFilter {
            if (this.name.lowercase().contains("debug")) {
                this.setSwazzlingEnabled(false) // https://embrace.io/docs/android/features/build-options/#disabling-swazzling-for-a-build-type
            }
        }
    }
```

`proguard-rules.pro`:
```
# Embrace https://embrace.io/docs/android/features/jetpack-compose/#set-proguard-rule
-keep class androidx.compose.ui.platform.AndroidComposeView {
    <fields>;
    <methods>;
}
```

Production `embrace-config.json`
```
{
  "app_id": "MWiq6",
  "api_token": "redacted",
  "sdk_config": {
    "compose": {
      "capture_compose_onclick": true
    }
  }
}
```

**Comment by eliabsisay** [comment]
@JakeSteam thank you for submitting the issue, one of our engineers will take a look and get back to you. If you find the frequency of this crash is increasing please let us know.

**Comment by fractalwrench** [comment]
@JakeSteam could you share the raw (txt) stacktrace from Crashlytics? I'd be interested to know if there are any additional embrace related frames that weren't highlighted as significant in Crashlytics UI, but are still useful for debugging this issue. I assume there's no message associated with the `Throwable` too?

**Comment by JakeSteam** [comment]
@fractalwrench Hey, we used to work on r/androiddev together! Small world.

Sure, here you go. It looks potentially keyboard related(?), and the very limited logs we have seem to show the user navigating to a signup screen (that has text fields) then back to our generic onboarding screen, if that helps at all.

I couldn't reproduce the crash, and it's still only happened to 1 user (on the oldish Android 12), so it's not super urgent on our side tbh.

```
          Fatal Exception: java.lang.IllegalStateException: Check failed.
       at androidx.compose.ui.node.DelegatableNodeKt.visitAncestors(DelegatableNode.kt:78)
       at androidx.compose.ui.focus.FocusTargetModifierNode.fetchFocusProperties$ui_release(FocusTargetModifierNode.kt:84)
       at androidx.compose.ui.focus.TwoDimensionalFocusSearchKt.collectAccessibleChildren(TwoDimensionalFocusSearch.kt:216)
       at androidx.compose.ui.focus.TwoDimensionalFocusSearchKt.findChildCorrespondingToFocusEnter--OM-vw8(TwoDimensionalFocusSearch.kt:121)
       at androidx.compose.ui.focus.TwoDimensionalFocusSearchKt.twoDimensionalFocusSearch--OM-vw8(TwoDimensionalFocusSearch.kt:96)
       at androidx.compose.ui.focus.FocusTraversalKt.focusSearch-sMXa3k8(FocusTraversal.kt:105)
       at androidx.compose.ui.focus.FocusOwnerImpl.moveFocus-3ESFkO8(FocusOwnerImpl.kt:150)
       at androidx.compose.ui.platform.AndroidComposeView$keyInputModifier$1.invoke-ZmokQxo(AndroidComposeView.android.kt:212)
       at androidx.compose.ui.platform.AndroidComposeView$keyInputModifier$1.invoke(AndroidComposeView.android.kt:207)
       at androidx.compose.ui.input.key.KeyInputInputModifierNodeImpl.onKeyEvent-ZmokQxo(KeyInputModifierNode.kt:97)
       at androidx.compose.ui.focus.FocusOwnerImpl.dispatchKeyEvent-ZmokQxo(FocusOwnerImpl.kt:180)
       at androidx.compose.ui.platform.AndroidComposeView.sendKeyEvent-ZmokQxo(AndroidComposeView.android.kt:631)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:639)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
       at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:486)
       at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1880)
       at android.app.Activity.dispatchKeyEvent(Activity.java:4159)
       at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
       at io.embrace.android.embracesdk.compose.internal.EmbraceWindowCallback.dispatchKeyEvent(EmbraceWindowCallback.kt)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:400)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6377)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6243)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5725)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5913)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5970)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5946)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6104)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3159)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2723)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2714)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3136)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:161)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
        
```

**Comment by fractalwrench** [comment]
@JakeSteam Small world indeed!

I had a look at this & the stacktrace contains Embrace's code that detects clicks in Compose UI, but the ultimate issue seems to be within the Compose code.

To give an explanation of what Embrace is doing behind the scenes, firstly the SDK sets a [callback on the window](https://github.com/embrace-io/embrace-android-sdk/blob/1c8e4abf7d8a7e605250c6aace01d7c13a10d4fe/embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/ComposeActivityListener.kt#L26). The callback is [implemented here](https://github.com/embrace-io/embrace-android-sdk/blob/1c8e4abf7d8a7e605250c6aace01d7c13a10d4fe/embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/internal/EmbraceWindowCallback.kt#L11) and ultimately delegates to the previous callback (if any was set). Because that class uses property delegation it results in Embrace showing up with a `dispatchKeyEvent` stackframe but ultimately we're just calling through to whatever callback was there before.

I'll close this for now as the implementation of those classes doesn't lead me to believe Embrace is causing this crash, but if you suspect otherwise or it becomes more of a problem please feel free to reopen & I'll take a look.

**Comment by JakeSteam** [comment]
Sounds good, I still think Embrace should have caught (& reported) the crash, but with a single occurrence we can both safely ignore it for now!

**Comment by JakeSteam** [comment]
FYI @fractalwrench whilst the root cause is still unknown & it's a v rare occurrence, I can confirm SDK v6.13.0 correctly reports this crash in Embrace now, thanks!
